# frozen_string_literal: true
# :markup: markdown

=begin
--
This file is generated by the templates/template.rb script and should not be
modified manually. See templates/lib/prism/mutation_compiler.rb.erb
if you are looking to modify the template
++
=end

module Prism
  # This visitor walks through the tree and copies each node as it is being
  # visited. This is useful for consumers that want to mutate the tree, as you
  # can change subtrees in place without effecting the rest of the tree.
  class MutationCompiler < Compiler
    def visit_alias_global_variable_node(node) # :nodoc:
      node.copy(new_name: visit(node.new_name), old_name: visit(node.old_name))
    end

    def visit_alias_method_node(node) # :nodoc:
      node.copy(new_name: visit(node.new_name), old_name: visit(node.old_name))
    end

    def visit_alternation_pattern_node(node) # :nodoc:
      node.copy(left: visit(node.left), right: visit(node.right))
    end

    def visit_and_node(node) # :nodoc:
      node.copy(left: visit(node.left), right: visit(node.right))
    end

    def visit_arguments_node(node) # :nodoc:
      node.copy(arguments: visit_all(node.arguments))
    end

    def visit_array_node(node) # :nodoc:
      node.copy(elements: visit_all(node.elements))
    end

    def visit_array_pattern_node(node) # :nodoc:
      node.copy(constant: visit(node.constant), requireds: visit_all(node.requireds), rest: visit(node.rest), posts: visit_all(node.posts))
    end

    def visit_assoc_node(node) # :nodoc:
      node.copy(key: visit(node.key), value: visit(node.value))
    end

    def visit_assoc_splat_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_back_reference_read_node(node) # :nodoc:
      node.copy
    end

    def visit_begin_node(node) # :nodoc:
      node.copy(statements: visit(node.statements), rescue_clause: visit(node.rescue_clause), else_clause: visit(node.else_clause), ensure_clause: visit(node.ensure_clause))
    end

    def visit_block_argument_node(node) # :nodoc:
      node.copy(expression: visit(node.expression))
    end

    def visit_block_local_variable_node(node) # :nodoc:
      node.copy
    end

    def visit_block_node(node) # :nodoc:
      node.copy(parameters: visit(node.parameters), body: visit(node.body))
    end

    def visit_block_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_block_parameters_node(node) # :nodoc:
      node.copy(parameters: visit(node.parameters), locals: visit_all(node.locals))
    end

    def visit_break_node(node) # :nodoc:
      node.copy(arguments: visit(node.arguments))
    end

    def visit_call_and_write_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), value: visit(node.value))
    end

    def visit_call_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), arguments: visit(node.arguments), block: visit(node.block))
    end

    def visit_call_operator_write_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), value: visit(node.value))
    end

    def visit_call_or_write_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), value: visit(node.value))
    end

    def visit_call_target_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver))
    end

    def visit_capture_pattern_node(node) # :nodoc:
      node.copy(value: visit(node.value), target: visit(node.target))
    end

    def visit_case_match_node(node) # :nodoc:
      node.copy(predicate: visit(node.predicate), conditions: visit_all(node.conditions), else_clause: visit(node.else_clause))
    end

    def visit_case_node(node) # :nodoc:
      node.copy(predicate: visit(node.predicate), conditions: visit_all(node.conditions), else_clause: visit(node.else_clause))
    end

    def visit_class_node(node) # :nodoc:
      node.copy(constant_path: visit(node.constant_path), superclass: visit(node.superclass), body: visit(node.body))
    end

    def visit_class_variable_and_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_class_variable_operator_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_class_variable_or_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_class_variable_read_node(node) # :nodoc:
      node.copy
    end

    def visit_class_variable_target_node(node) # :nodoc:
      node.copy
    end

    def visit_class_variable_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_constant_and_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_constant_operator_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_constant_or_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_constant_path_and_write_node(node) # :nodoc:
      node.copy(target: visit(node.target), value: visit(node.value))
    end

    def visit_constant_path_node(node) # :nodoc:
      node.copy(parent: visit(node.parent))
    end

    def visit_constant_path_operator_write_node(node) # :nodoc:
      node.copy(target: visit(node.target), value: visit(node.value))
    end

    def visit_constant_path_or_write_node(node) # :nodoc:
      node.copy(target: visit(node.target), value: visit(node.value))
    end

    def visit_constant_path_target_node(node) # :nodoc:
      node.copy(parent: visit(node.parent))
    end

    def visit_constant_path_write_node(node) # :nodoc:
      node.copy(target: visit(node.target), value: visit(node.value))
    end

    def visit_constant_read_node(node) # :nodoc:
      node.copy
    end

    def visit_constant_target_node(node) # :nodoc:
      node.copy
    end

    def visit_constant_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_def_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), parameters: visit(node.parameters), body: visit(node.body))
    end

    def visit_defined_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_else_node(node) # :nodoc:
      node.copy(statements: visit(node.statements))
    end

    def visit_embedded_statements_node(node) # :nodoc:
      node.copy(statements: visit(node.statements))
    end

    def visit_embedded_variable_node(node) # :nodoc:
      node.copy(variable: visit(node.variable))
    end

    def visit_ensure_node(node) # :nodoc:
      node.copy(statements: visit(node.statements))
    end

    def visit_false_node(node) # :nodoc:
      node.copy
    end

    def visit_find_pattern_node(node) # :nodoc:
      node.copy(constant: visit(node.constant), left: visit(node.left), requireds: visit_all(node.requireds), right: visit(node.right))
    end

    def visit_flip_flop_node(node) # :nodoc:
      node.copy(left: visit(node.left), right: visit(node.right))
    end

    def visit_float_node(node) # :nodoc:
      node.copy
    end

    def visit_for_node(node) # :nodoc:
      node.copy(index: visit(node.index), collection: visit(node.collection), statements: visit(node.statements))
    end

    def visit_forwarding_arguments_node(node) # :nodoc:
      node.copy
    end

    def visit_forwarding_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_forwarding_super_node(node) # :nodoc:
      node.copy(block: visit(node.block))
    end

    def visit_global_variable_and_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_global_variable_operator_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_global_variable_or_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_global_variable_read_node(node) # :nodoc:
      node.copy
    end

    def visit_global_variable_target_node(node) # :nodoc:
      node.copy
    end

    def visit_global_variable_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_hash_node(node) # :nodoc:
      node.copy(elements: visit_all(node.elements))
    end

    def visit_hash_pattern_node(node) # :nodoc:
      node.copy(constant: visit(node.constant), elements: visit_all(node.elements), rest: visit(node.rest))
    end

    def visit_if_node(node) # :nodoc:
      node.copy(predicate: visit(node.predicate), statements: visit(node.statements), subsequent: visit(node.subsequent))
    end

    def visit_imaginary_node(node) # :nodoc:
      node.copy(numeric: visit(node.numeric))
    end

    def visit_implicit_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_implicit_rest_node(node) # :nodoc:
      node.copy
    end

    def visit_in_node(node) # :nodoc:
      node.copy(pattern: visit(node.pattern), statements: visit(node.statements))
    end

    def visit_index_and_write_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), arguments: visit(node.arguments), block: visit(node.block), value: visit(node.value))
    end

    def visit_index_operator_write_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), arguments: visit(node.arguments), block: visit(node.block), value: visit(node.value))
    end

    def visit_index_or_write_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), arguments: visit(node.arguments), block: visit(node.block), value: visit(node.value))
    end

    def visit_index_target_node(node) # :nodoc:
      node.copy(receiver: visit(node.receiver), arguments: visit(node.arguments), block: visit(node.block))
    end

    def visit_instance_variable_and_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_instance_variable_operator_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_instance_variable_or_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_instance_variable_read_node(node) # :nodoc:
      node.copy
    end

    def visit_instance_variable_target_node(node) # :nodoc:
      node.copy
    end

    def visit_instance_variable_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_integer_node(node) # :nodoc:
      node.copy
    end

    def visit_interpolated_match_last_line_node(node) # :nodoc:
      node.copy(parts: visit_all(node.parts))
    end

    def visit_interpolated_regular_expression_node(node) # :nodoc:
      node.copy(parts: visit_all(node.parts))
    end

    def visit_interpolated_string_node(node) # :nodoc:
      node.copy(parts: visit_all(node.parts))
    end

    def visit_interpolated_symbol_node(node) # :nodoc:
      node.copy(parts: visit_all(node.parts))
    end

    def visit_interpolated_x_string_node(node) # :nodoc:
      node.copy(parts: visit_all(node.parts))
    end

    def visit_it_local_variable_read_node(node) # :nodoc:
      node.copy
    end

    def visit_it_parameters_node(node) # :nodoc:
      node.copy
    end

    def visit_keyword_hash_node(node) # :nodoc:
      node.copy(elements: visit_all(node.elements))
    end

    def visit_keyword_rest_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_lambda_node(node) # :nodoc:
      node.copy(parameters: visit(node.parameters), body: visit(node.body))
    end

    def visit_local_variable_and_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_local_variable_operator_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_local_variable_or_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_local_variable_read_node(node) # :nodoc:
      node.copy
    end

    def visit_local_variable_target_node(node) # :nodoc:
      node.copy
    end

    def visit_local_variable_write_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_match_last_line_node(node) # :nodoc:
      node.copy
    end

    def visit_match_predicate_node(node) # :nodoc:
      node.copy(value: visit(node.value), pattern: visit(node.pattern))
    end

    def visit_match_required_node(node) # :nodoc:
      node.copy(value: visit(node.value), pattern: visit(node.pattern))
    end

    def visit_match_write_node(node) # :nodoc:
      node.copy(call: visit(node.call), targets: visit_all(node.targets))
    end

    def visit_missing_node(node) # :nodoc:
      node.copy
    end

    def visit_module_node(node) # :nodoc:
      node.copy(constant_path: visit(node.constant_path), body: visit(node.body))
    end

    def visit_multi_target_node(node) # :nodoc:
      node.copy(lefts: visit_all(node.lefts), rest: visit(node.rest), rights: visit_all(node.rights))
    end

    def visit_multi_write_node(node) # :nodoc:
      node.copy(lefts: visit_all(node.lefts), rest: visit(node.rest), rights: visit_all(node.rights), value: visit(node.value))
    end

    def visit_next_node(node) # :nodoc:
      node.copy(arguments: visit(node.arguments))
    end

    def visit_nil_node(node) # :nodoc:
      node.copy
    end

    def visit_no_keywords_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_numbered_parameters_node(node) # :nodoc:
      node.copy
    end

    def visit_numbered_reference_read_node(node) # :nodoc:
      node.copy
    end

    def visit_optional_keyword_parameter_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_optional_parameter_node(node) # :nodoc:
      node.copy(value: visit(node.value))
    end

    def visit_or_node(node) # :nodoc:
      node.copy(left: visit(node.left), right: visit(node.right))
    end

    def visit_parameters_node(node) # :nodoc:
      node.copy(requireds: visit_all(node.requireds), optionals: visit_all(node.optionals), rest: visit(node.rest), posts: visit_all(node.posts), keywords: visit_all(node.keywords), keyword_rest: visit(node.keyword_rest), block: visit(node.block))
    end

    def visit_parentheses_node(node) # :nodoc:
      node.copy(body: visit(node.body))
    end

    def visit_pinned_expression_node(node) # :nodoc:
      node.copy(expression: visit(node.expression))
    end

    def visit_pinned_variable_node(node) # :nodoc:
      node.copy(variable: visit(node.variable))
    end

    def visit_post_execution_node(node) # :nodoc:
      node.copy(statements: visit(node.statements))
    end

    def visit_pre_execution_node(node) # :nodoc:
      node.copy(statements: visit(node.statements))
    end

    def visit_program_node(node) # :nodoc:
      node.copy(statements: visit(node.statements))
    end

    def visit_range_node(node) # :nodoc:
      node.copy(left: visit(node.left), right: visit(node.right))
    end

    def visit_rational_node(node) # :nodoc:
      node.copy
    end

    def visit_redo_node(node) # :nodoc:
      node.copy
    end

    def visit_regular_expression_node(node) # :nodoc:
      node.copy
    end

    def visit_required_keyword_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_required_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_rescue_modifier_node(node) # :nodoc:
      node.copy(expression: visit(node.expression), rescue_expression: visit(node.rescue_expression))
    end

    def visit_rescue_node(node) # :nodoc:
      node.copy(exceptions: visit_all(node.exceptions), reference: visit(node.reference), statements: visit(node.statements), subsequent: visit(node.subsequent))
    end

    def visit_rest_parameter_node(node) # :nodoc:
      node.copy
    end

    def visit_retry_node(node) # :nodoc:
      node.copy
    end

    def visit_return_node(node) # :nodoc:
      node.copy(arguments: visit(node.arguments))
    end

    def visit_self_node(node) # :nodoc:
      node.copy
    end

    def visit_shareable_constant_node(node) # :nodoc:
      node.copy(write: visit(node.write))
    end

    def visit_singleton_class_node(node) # :nodoc:
      node.copy(expression: visit(node.expression), body: visit(node.body))
    end

    def visit_source_encoding_node(node) # :nodoc:
      node.copy
    end

    def visit_source_file_node(node) # :nodoc:
      node.copy
    end

    def visit_source_line_node(node) # :nodoc:
      node.copy
    end

    def visit_splat_node(node) # :nodoc:
      node.copy(expression: visit(node.expression))
    end

    def visit_statements_node(node) # :nodoc:
      node.copy(body: visit_all(node.body))
    end

    def visit_string_node(node) # :nodoc:
      node.copy
    end

    def visit_super_node(node) # :nodoc:
      node.copy(arguments: visit(node.arguments), block: visit(node.block))
    end

    def visit_symbol_node(node) # :nodoc:
      node.copy
    end

    def visit_true_node(node) # :nodoc:
      node.copy
    end

    def visit_undef_node(node) # :nodoc:
      node.copy(names: visit_all(node.names))
    end

    def visit_unless_node(node) # :nodoc:
      node.copy(predicate: visit(node.predicate), statements: visit(node.statements), else_clause: visit(node.else_clause))
    end

    def visit_until_node(node) # :nodoc:
      node.copy(predicate: visit(node.predicate), statements: visit(node.statements))
    end

    def visit_when_node(node) # :nodoc:
      node.copy(conditions: visit_all(node.conditions), statements: visit(node.statements))
    end

    def visit_while_node(node) # :nodoc:
      node.copy(predicate: visit(node.predicate), statements: visit(node.statements))
    end

    def visit_x_string_node(node) # :nodoc:
      node.copy
    end

    def visit_yield_node(node) # :nodoc:
      node.copy(arguments: visit(node.arguments))
    end
  end
end
